Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,4 +1,3 @@
-# .github/actions/code-of-conduct-analyzer/action.yml
 name: 'Code of Conduct Analyzer'
 description: 'Validates the Code of Conduct file in the repository, performs analysis, and triggers workflows based on the result'
 author: 'CobosDS'
@@ -90,6 +89,10 @@ runs:
       shell: bash
       run: |
         response=$(curl -s -X POST "${{ inputs.server_url }}" -H "Content-Type: application/json" --data @data/payload.json)
+        if [ -z "$response" ]; then
+          echo "Error: No response from server."
+          exit 1
+        fi
         echo "$response" > data/response.json
         cat data/response.json
 
